### ISSUE TITLE
Allow node version to be specified

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/action-update-wordpress-plugin#9]
### Description

I would like the ability to specify a node version when running this action, since not all projects use the same version of node.

### Use Case

When a user uses this action, they should be able to specify the version of node they want it to use.

## Acceptance Criteria

- Allow the version of node used in the action to be specified as a parameter when the action is run.
- If the version of node is not specified, default it to `lts`.

**Comment by benpbolton** [comment]
This should be done. You'll need to be on version `latest` or https://github.com/alleyinteractive/action-update-wordpress-plugin/releases/tag/v2.0.0 to take advantage of the new `node-version` input
